runtime: php73
env: standard

handlers:
  # Tài nguyên tĩnh (assets, img, css, js)
  - url: /assets
    static_dir: assets

  - url: /img
    static_dir: img

  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  # Xử lý tất cả các yêu cầu còn lại cho các file PHP (trừ các file tĩnh)
  - url: /.*  
    script: auto
