runtime: php83
env: standard

handlers:
# Serve a directory as a static resource.
- url: src\assets\js
  static_dir: js
# Serve a directory as a static resource.
- url: src\assets\css
  static_dir: css
# Serve a directory as a static resource.
- url: src\assets\scss
  static_dir: scss
# Serve a directory as a static resource.
- url: src\assets\images
  static_dir: images
# Serve a directory as a static resource.
- url: src\assets\libs
  static_dir: libs


# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto