runtime: php73
env: standard

handlers:
  # Tài nguyên tĩnh (assets, img, css, js)
  - url: /hrm
    static_dir: hrm

  # Xử lý tất cả các yêu cầu còn lại cho các file PHP (trừ các file tĩnh)
  - url: /.*  
    script: auto
